### ISSUE TITLE
I have a question about build

### ISSUE THREAD

**Issue by MinHyeong-Lee** [chrishoage/spleeb#1]
Hi friend, I build spleeb keyboard that you designed these days. I have a few questions. I'm a beginner. :(

**Image for Q1, Q2 https://postimg.cc/DWTQpYrH**

**Q1 (Green Color)**. What is this? Should I solder here any components???

**Q2 (Red Color)** . Is the diode direction of the part I marked in red the right direction?

-----
**Image for Q3 https://postimg.cc/bsBdv63M**

**Q3**. Should I build in the order of the pictures? Is this right? layer 0 (MX switch) layer 1 (spleeb plate) layer 2 (spleeb pcb, with soldered diode, rotary encoder) layer 3 (PJ-320A 3.5 mm jack, MCU)

I drew with my hands because I am not good at English. I hope you can understand.

Your keyboard is so cool. I'll make sure to build it and send you a picture

Thank you.

**Comment by chrishoage** [comment]
> Q1 (Green Color). What is this? Should I solder here any components???

Thank you for pointing this out! I had accidentally kept this out of the BOM

I have updated it here https://github.com/chrishoage/spleeb/commit/5231b6fe8878e6d334b1f7b3b07c349e56742b73

> Q2 (Red Color) . Is the diode direction of the part I marked in red the right direction?

Yes the diode direction correct. The silkscreen makes it hard to tell, but another way is to use the square pad as an indicator. The square pad is the direction of the cathode part of the diode. 

> Q3. Should I build in the order of the pictures? Is this right? layer 0 (MX switch) layer 1 (spleeb plate) layer 2 (spleeb pcb, with soldered diode, rotary encoder) layer 3 (PJ-320A 3.5 mm jack, MCU)

Yes that is all correct. The "side" you solder the diodes to don't matter. I soldered my diodes underneath the PCB but it was just personal preference.

The most important part is the MCU orientation which it seems you got correct from your drawing.

You would solder the pads on the opposite side of the MCU
