### ISSUE TITLE
compile firmware issue

### ISSUE THREAD

**Issue by MinHyeong-Lee** [chrishoage/spleeb#2]
Thank you for your answer last time, it was very helpful. 👍

I have a new problem 😢
An error occurred while compiling firmware.

![image](https://user-images.githubusercontent.com/48749902/234615430-0e5785a5-1cf0-4d83-bd0d-b4cb2c5beff8.png)

default keymap compile works well
but your keymap not work on my env :(

Q1. How can I compile keymap chrishoage?

Q2. I used for build spleeb with MCU KB2040
<img width="595" alt="image" src="https://user-images.githubusercontent.com/48749902/234617193-bebb8904-fd41-4c8b-8ddf-4318f84d3b9b.png">

<img width="358" alt="image" src="https://user-images.githubusercontent.com/48749902/234617264-fb8a54af-040b-4004-9911-78556527a1b8.png">

The pinout of each mcu seems to be slightly different. Should I fix some code when compiling firmware?

Thank you.

**Comment by chrishoage** [comment]
I can reproduce the compile errors. It looks like things changed since I wrote the original firmware and broke my keymap. 

I will spend some time this week/weekend to open a PR for QMK to fix the keyamp 

> Q2. I used for build spleeb with MCU KB2040
> The pinout of each mcu seems to be slightly different. Should I fix some code when compiling firmware?

Yes you will need to update the pins in the firmware to mach any pin changes. It looks like the KB2040 only has a few pins different, so it should be a simple update. 

You can use the `default` firmware to ensure the pins are correct.

**Comment by chrishoage** [comment]
```diff
diff --git a/keyboards/spleeb/keymaps/chrishoage/keymap.c b/keyboards/spleeb/keymaps/chrishoage/keymap.c
index 2650c1aebf..c3dfb8f02b 100644
--- a/keyboards/spleeb/keymaps/chrishoage/keymap.c
+++ b/keyboards/spleeb/keymaps/chrishoage/keymap.c
@@ -4,7 +4,7 @@
 #include QMK_KEYBOARD_H
 
 // Double tap TD(0) to enter bootloader
-static void enter_qk_boot(qk_tap_dance_state_t *state, void *user_data) {
+static void enter_qk_boot(tap_dance_state_t *state, void *user_data) {
     if (state->count >= 2) {
         reset_keyboard();
         reset_tap_dance(state);
@@ -13,7 +13,7 @@ static void enter_qk_boot(qk_tap_dance_state_t *state, void *user_data) {
 
 enum SpleebLayer { _BASE = 0, _FN, _MOUSE };
 
-qk_tap_dance_action_t tap_dance_actions[] = {[0] = ACTION_TAP_DANCE_FN(enter_qk_boot)};
+tap_dance_action_t tap_dance_actions[] = {[0] = ACTION_TAP_DANCE_FN(enter_qk_boot)};
 
 // clang-format off
 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
```

I have not loaded it onto my keyboard yet to test but this diff makes my keymap compile. 

I will open a PR to QMK as soon as I can verify the firmware on my keyboard

**Comment by chrishoage** [comment]
@MinHyeong-Lee I have opened a PR to fix it in QMK https://github.com/qmk/qmk_firmware/pull/20644

The branch in the PR will allow you to build (I have verified with my own keyboard)

**Comment by MinHyeong-Lee** [comment]
> @MinHyeong-Lee I have opened a PR to fix it in QMK [qmk/qmk_firmware#20644](https://github.com/qmk/qmk_firmware/pull/20644)
> 
> The branch in the PR will allow you to build (I have verified with my own keyboard)

I checked that your PR was merged. Compile firmware also works well. Thank you!!

By the way, can I ask you one more time about the direction of soldering?
![image](https://user-images.githubusercontent.com/48749902/235425899-0c8438bf-8186-43f5-b8b4-205eecdcfdff.png)

I soldered my KB2040 under the spleeb PCB, and soldered solder pads same direction with switches
Is this right??

Thank you :)

**Comment by chrishoage** [comment]
> soldered solder pads same direction with switches. Is this right??

Unfortunately no, forgive my poor explanation in the readme. 

You need to solder the pads on the side the switches are facing, not the side the switches are soldered. 

The pads should be soldered on the opposite side of the MCU when the MCU is in the orientation you have it. 

You will need to de-solder the MCU, wick up the solder on the pads (ensure there is no bridge) then resolder the MCU. 

The MCU is correct in your picture, however the pads should not be soldered on the same side.

**Comment by chrishoage** [comment]
@MinHyeong-Lee In my most recent commit (https://github.com/chrishoage/spleeb/commit/7b96cb6b1492c2ee43bb1804438142b8a255d928) I have added photos to help better demonstrate the correct place to solder the pads. 

Apologies for the confusion

**Comment by MinHyeong-Lee** [comment]
> @MinHyeong-Lee In my most recent commit ([7b96cb6](https://github.com/chrishoage/spleeb/commit/7b96cb6b1492c2ee43bb1804438142b8a255d928)) I have added photos to help better demonstrate the correct place to solder the pads.
> 
> Apologies for the confusion

Thank you. It helped me a lot!! :)
