### ISSUE TITLE
More build info please

### ISSUE THREAD

**Issue by pokeygithub** [chrishoage/spleeb#4]
I have ordered the PCBs and they have come in.  Is there a place that documents (with images) the soldering and connections to the touchpad?  I am really excited to move forward but doubt my smarts.

**Comment by chrishoage** [comment]
There are build notes here https://github.com/chrishoage/spleeb?tab=readme-ov-file#build-notes which I improved after discussion from https://github.com/chrishoage/spleeb/issues/1

If there is anything unclear please let me know and I can try to improve it further!

**Comment by memoriasIT** [comment]
I am currently in the process of building this too. I was a big noob, so I also struggled. I will try to make a PR with a more noob friendly build notes.

I am currently trying to work on the firmware. 

Edit: to OP. Please see closed issues, there's some issues that really helped me check how everything should be connected.

**Comment by pokeygithub** [comment]
I think what would help greatly are pictures of the completed boards without the case.  Then I can reference how it should look compared to what I have done.   Like the MCU images are great, but it would be awesome to reference the other steps as well.

**Comment by chrishoage** [comment]
Sure next time I disassemble my case I'll take some pictures of the completed boards. 

Should be in the next few weeks. I've been working on improvements to the trackpad holder (the old one is so terrible!) and adding tenting legs

**Comment by memoriasIT** [comment]
@pokeygithub I will try to add them to this issue today!

@chrishoage And those are awesome news! I will wait for that then! 😄 
Awesome project as a whole btw, love it!

**Comment by chrishoage** [comment]
@pokeygithub I took apart the right half and took these pictures. Is this what you're looking for? If so I can add these to the readme when I publish the 3d model updates for the chassis 

![PXL_20240728_005149489](https://github.com/user-attachments/assets/293edcab-ec87-4702-905a-0bfd310f19f3)

![PXL_20240728_005955732](https://github.com/user-attachments/assets/000564f5-6228-4946-8b8a-8158f18f0fa9)

![PXL_20240728_010011605](https://github.com/user-attachments/assets/60bec008-1a9f-4edc-ab8d-22450206e00f)


A bonus picture of the prototype Cirque bracket and tenting legs. Both still need a little more work before they can be shared. Hopefully in a couple more weeks they will be ready! 

![PXL_20240728_020800133 MP](https://github.com/user-attachments/assets/94bd54ec-79fc-4ace-a26d-d2cbd0fc6ddc)

**Comment by memoriasIT** [comment]
Looks quite promising! Waiting for the files! ❤️
I will also share all I have here for someone in the future.

![IMG-20240629-WA0007.jpeg](https://github.com/user-attachments/assets/b1245489-1bd7-4d6e-aced-f415c9955abe)

My Cirque TouchPad came with a ribbon to make it easier to solder so I used it.
![20240706_141022.jpg](https://github.com/user-attachments/assets/c0f63fe7-bbea-4d6a-9d79-811627a14e79)

The tolerances were way too tight and I couldn't solder the cables, so I cut a bit from the right just to make a direct pass.
![IMG-20240712-WA0006.jpg](https://github.com/user-attachments/assets/6866e931-1d68-452c-ba2f-ac9914929324)

**Comment by memoriasIT** [comment]
Looks quite promising! Waiting for the files! ❤️
I will also share all I have here for someone in the future.

My Cirque TouchPad came with a ribbon to make it easier to solder so I used it.
![20240706_141022.jpg](https://github.com/user-attachments/assets/c0f63fe7-bbea-4d6a-9d79-811627a14e79)

The tolerances were way too tight and I couldn't solder the cables, so I cut a bit from the right just to make a direct pass.
![IMG-20240712-WA0006.jpg](https://github.com/user-attachments/assets/6866e931-1d68-452c-ba2f-ac9914929324)

**Comment by pokeygithub** [comment]
I really appreciate it everyone.  Now I can get to building with full confidence that I am soldering things on the correct side of the board with correct orientation!

**Comment by chrishoage** [comment]
Something that helped me when I was building my boards was to place some masking tape on each to write "Left" and "Right" so I didn't confuse them while adding components

**Comment by pokeygithub** [comment]
Making progress.

![20240814_191912](https://github.com/user-attachments/assets/2c52d5ef-ffc7-4dbd-a825-2e0e8907c0e5)

**Comment by chrishoage** [comment]
I took away the tenting legs because I was unhappy with them, but the Cirque touchpad was ready for release. 

You can read about everything in the pull request which added it 

https://github.com/chrishoage/spleeb/pull/5

**Comment by memoriasIT** [comment]
Lovely! Can I use the new Cirque enclosure with the old chassis? I assume yes?

**Comment by chrishoage** [comment]
No if you print the files as-is they will not work as the footprint of the Cirque enclosure has changed. You may be able to _make_ it fit with some physical modifications to either the top of the chassis or the Cirque enclosure but I've never tried this so YMMV

There were a number of other changes I wanted to make to the chassis so none of the original printed parts will carry over with the new ones. 

I go into detail with what has changed in the PR I linked
